import {Poppins } from "next/font/google";
import "./globals.css";
import Footer from "../../Component/Footer/Footer";

export const metadata = {
  title: "Restaurant",
  description: "Generated by Abu Fattah Md Shakib",
};


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'], 
  display: 'swap',
});


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        {children}
         <Footer />
      </body>
    </html>
  );
}
